// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChuu3vRWpjiYs5l3dMYTqH2CDBRMvSlkM',
    appId: '1:487440786887:web:ab597c0d826559cd2425e2',
    messagingSenderId: '487440786887',
    projectId: 'chat-app-335e6',
    authDomain: 'chat-app-335e6.firebaseapp.com',
    storageBucket: 'chat-app-335e6.firebasestorage.app',
    measurementId: 'G-BD1DQGL4QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXpZ4ntALYuCN_a5Em_T9-PaHi8IVKA8',
    appId: '1:487440786887:android:8bd92b8244649eaf2425e2',
    messagingSenderId: '487440786887',
    projectId: 'chat-app-335e6',
    storageBucket: 'chat-app-335e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANmxgXJjDb-l0GuH1ULAN-znzYElOy10',
    appId: '1:487440786887:ios:e90d22e48f18dbc22425e2',
    messagingSenderId: '487440786887',
    projectId: 'chat-app-335e6',
    storageBucket: 'chat-app-335e6.firebasestorage.app',
    iosBundleId: 'artech.chat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBANmxgXJjDb-l0GuH1ULAN-znzYElOy10',
    appId: '1:487440786887:ios:e90d22e48f18dbc22425e2',
    messagingSenderId: '487440786887',
    projectId: 'chat-app-335e6',
    storageBucket: 'chat-app-335e6.firebasestorage.app',
    iosBundleId: 'artech.chat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChuu3vRWpjiYs5l3dMYTqH2CDBRMvSlkM',
    appId: '1:487440786887:web:dc6fa73d2af138462425e2',
    messagingSenderId: '487440786887',
    projectId: 'chat-app-335e6',
    authDomain: 'chat-app-335e6.firebaseapp.com',
    storageBucket: 'chat-app-335e6.firebasestorage.app',
    measurementId: 'G-6VE5M28VXT',
  );

}